# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "C:\\Users\\vladx\\RiderProjects\\ElegantDatabasePackages"
      dockerfile: "Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "api:dev"
    ports: []
    volumes:
    - "C:\\Users\\vladx\\RiderProjects\\ElegantDatabasePackages\\Api:/app:rw"
    working_dir: "/app"
